############ DO NOT CHANGE THESE #################
INCDIR:=../:./common_bsv
MASTERS=2
SLAVES=5
############# User changes to be done below #################
TOP_MODULE:=mkinst_withxactors
TOP_DIR:=./
TOP_FILE:=synth_instance.bsv

