############ DO NOT CHANGE THESE #################
INCDIR:=../:./common_bsv:../../axi4:../../apb
MASTERS=2
SLAVES=5
############# User changes to be done below #################
TOP_MODULE:=mkinst_bridge
TOP_DIR:=../
TOP_FILE:=axi2apb.bsv

