############ DO NOT CHANGE THESE #################
INCDIR:=../:./common_bsv
############# User changes to be done below #################
TOP_MODULE:=mkinst_withxactors
TOP_DIR:=./
TOP_FILE:=synth_instance.bsv

