############ DO NOT CHANGE THESE #################
INCDIR:=../:./common_bsv
############# User changes to be done below #################
TOP_MODULE:=mkinstance
TOP_DIR:=./
TOP_FILE:=AXI4_instance.bsv

